### ISSUE TITLE
Where is the data?

### ISSUE THREAD

**Issue by amitbinu** [ash47/TimetableGenerator#4]
Hey!

After we npm install, timetable.js uses the timetable folder, but there is no data in there. This leads to a failed search every time. Could you please help? Thanks !

**Comment by ash47** [comment]
Hi there, sorry for the delay!

This appears to be because UoM changed their API! As a simple example of seeing this work, fire up the app, browse to it in your web browser, and then change the year to 2014, search for "SWEN" and select the first subject it finds.

I'll take a quick look at their new API now, but, if it takes me longer than 20 minutes to find it, then I probably won't be updating it.

**Comment by ash47** [comment]
Fixed! Working now, enjoy!

**Comment by amitbinu** [comment]
Thank you so much!

**Comment by nuclearpidgeon** [comment]
@ash47 thank you so much for patching this for 2017+!!! Big up for supporting old software :pray:

**Comment by ash47** [comment]
Is it broken again?

**Comment by ash47** [comment]
Just tested it, looks like it's working for me
